package com.otaku_tamashi.app.POJO.DO;

import java.util.Date;

public class AniDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animelist.id
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animelist.name
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animelist.font
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    private String font;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animelist.platform
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    private String platform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animelist.url
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animelist.date
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animelist.id
     *
     * @return the value of animelist.id
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animelist.id
     *
     * @param id the value for animelist.id
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animelist.name
     *
     * @return the value of animelist.name
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animelist.name
     *
     * @param name the value for animelist.name
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animelist.font
     *
     * @return the value of animelist.font
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public String getFont() {
        return font;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animelist.font
     *
     * @param font the value for animelist.font
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public void setFont(String font) {
        this.font = font == null ? null : font.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animelist.platform
     *
     * @return the value of animelist.platform
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animelist.platform
     *
     * @param platform the value for animelist.platform
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animelist.url
     *
     * @return the value of animelist.url
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animelist.url
     *
     * @param url the value for animelist.url
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animelist.date
     *
     * @return the value of animelist.date
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animelist.date
     *
     * @param date the value for animelist.date
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anime.name
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anime.image
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anime.tv
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    private String tv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anime.staff
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    private String staff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anime.voice
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    private String voice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anime.js
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    private String js;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anime.list_id
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    private Long listId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anime.id
     *
     * @return the value of anime.id
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anime.id
     *
     * @param id the value for anime.id
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anime.name
     *
     * @return the value of anime.name
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anime.name
     *
     * @param name the value for anime.name
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anime.image
     *
     * @return the value of anime.image
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anime.image
     *
     * @param image the value for anime.image
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anime.tv
     *
     * @return the value of anime.tv
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    public String getTv() {
        return tv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anime.tv
     *
     * @param tv the value for anime.tv
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    public void setTv(String tv) {
        this.tv = tv == null ? null : tv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anime.staff
     *
     * @return the value of anime.staff
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    public String getStaff() {
        return staff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anime.staff
     *
     * @param staff the value for anime.staff
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    public void setStaff(String staff) {
        this.staff = staff == null ? null : staff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anime.voice
     *
     * @return the value of anime.voice
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    public String getVoice() {
        return voice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anime.voice
     *
     * @param voice the value for anime.voice
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    public void setVoice(String voice) {
        this.voice = voice == null ? null : voice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anime.js
     *
     * @return the value of anime.js
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    public String getJs() {
        return js;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anime.js
     *
     * @param js the value for anime.js
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    public void setJs(String js) {
        this.js = js == null ? null : js.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anime.list_id
     *
     * @return the value of anime.list_id
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    public Long getListId() {
        return listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anime.list_id
     *
     * @param listId the value for anime.list_id
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    public void setListId(Long listId) {
        this.listId = listId;
    }
}
