package com.otaku_tamashi.app.POJO.DO;

import java.util.Date;

public class AnimeDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animelist.id
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animelist.name
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animelist.font
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    private String font;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animelist.platform
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    private String platform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animelist.url
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animelist.date
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animelist.id
     *
     * @return the value of animelist.id
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animelist.id
     *
     * @param id the value for animelist.id
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animelist.name
     *
     * @return the value of animelist.name
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animelist.name
     *
     * @param name the value for animelist.name
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animelist.font
     *
     * @return the value of animelist.font
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public String getFont() {
        return font;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animelist.font
     *
     * @param font the value for animelist.font
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public void setFont(String font) {
        this.font = font == null ? null : font.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animelist.platform
     *
     * @return the value of animelist.platform
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animelist.platform
     *
     * @param platform the value for animelist.platform
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animelist.url
     *
     * @return the value of animelist.url
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animelist.url
     *
     * @param url the value for animelist.url
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animelist.date
     *
     * @return the value of animelist.date
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animelist.date
     *
     * @param date the value for animelist.date
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }
}