package com.otaku_tamashi.app.POJO.DO;

public class FavouriteDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favourite.id
     *
     * @mbg.generated Tue Apr 09 16:48:52 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favourite.listid
     *
     * @mbg.generated Tue Apr 09 16:48:52 CST 2019
     */
    private Long listid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favourite.username
     *
     * @mbg.generated Tue Apr 09 16:48:52 CST 2019
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favourite.id
     *
     * @return the value of favourite.id
     *
     * @mbg.generated Tue Apr 09 16:48:52 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favourite.id
     *
     * @param id the value for favourite.id
     *
     * @mbg.generated Tue Apr 09 16:48:52 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favourite.listid
     *
     * @return the value of favourite.listid
     *
     * @mbg.generated Tue Apr 09 16:48:52 CST 2019
     */
    public Long getListid() {
        return listid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favourite.listid
     *
     * @param listid the value for favourite.listid
     *
     * @mbg.generated Tue Apr 09 16:48:52 CST 2019
     */
    public void setListid(Long listid) {
        this.listid = listid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favourite.username
     *
     * @return the value of favourite.username
     *
     * @mbg.generated Tue Apr 09 16:48:52 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favourite.username
     *
     * @param username the value for favourite.username
     *
     * @mbg.generated Tue Apr 09 16:48:52 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }
}