package com.otaku_tamashi.app.POJO.DO;

public class NewsDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbg.generated Mon Apr 08 19:34:46 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbg.generated Mon Apr 08 19:34:46 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.content
     *
     * @mbg.generated Mon Apr 08 19:34:46 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.image
     *
     * @mbg.generated Mon Apr 08 19:34:46 CST 2019
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.list_id
     *
     * @mbg.generated Mon Apr 08 19:34:46 CST 2019
     */
    private Long listId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.ltitle
     *
     * @mbg.generated Mon Apr 08 19:34:46 CST 2019
     */
    private String ltitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbg.generated Mon Apr 08 19:34:46 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbg.generated Mon Apr 08 19:34:46 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbg.generated Mon Apr 08 19:34:46 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbg.generated Mon Apr 08 19:34:46 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.content
     *
     * @return the value of news.content
     *
     * @mbg.generated Mon Apr 08 19:34:46 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.content
     *
     * @param content the value for news.content
     *
     * @mbg.generated Mon Apr 08 19:34:46 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.image
     *
     * @return the value of news.image
     *
     * @mbg.generated Mon Apr 08 19:34:46 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.image
     *
     * @param image the value for news.image
     *
     * @mbg.generated Mon Apr 08 19:34:46 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.list_id
     *
     * @return the value of news.list_id
     *
     * @mbg.generated Mon Apr 08 19:34:46 CST 2019
     */
    public Long getListId() {
        return listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.list_id
     *
     * @param listId the value for news.list_id
     *
     * @mbg.generated Mon Apr 08 19:34:46 CST 2019
     */
    public void setListId(Long listId) {
        this.listId = listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.ltitle
     *
     * @return the value of news.ltitle
     *
     * @mbg.generated Mon Apr 08 19:34:46 CST 2019
     */
    public String getLtitle() {
        return ltitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.ltitle
     *
     * @param ltitle the value for news.ltitle
     *
     * @mbg.generated Mon Apr 08 19:34:46 CST 2019
     */
    public void setLtitle(String ltitle) {
        this.ltitle = ltitle == null ? null : ltitle.trim();
    }
}