package com.otaku_tamashi.app.POJO.DO;

public class UserLoginDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.id
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.username
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.password
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.id
     *
     * @return the value of user_login.id
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.id
     *
     * @param id the value for user_login.id
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.username
     *
     * @return the value of user_login.username
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.username
     *
     * @param username the value for user_login.username
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.password
     *
     * @return the value of user_login.password
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.password
     *
     * @param password the value for user_login.password
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}