package com.otaku_tamashi.app.Dao;

import com.otaku_tamashi.app.POJO.DO.AdminDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AdminDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Tue Apr 09 19:47:29 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Tue Apr 09 19:47:29 CST 2019
     */
    int insert(AdminDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Tue Apr 09 19:47:29 CST 2019
     */
    int insertSelective(AdminDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Tue Apr 09 19:47:29 CST 2019
     */
    AdminDO selectByPrimaryKey(Long id);
    AdminDO selectByAdminnameAndPassword(@Param(value = "username") String username,@Param(value = "password") String password);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Tue Apr 09 19:47:29 CST 2019
     */
    int updateByPrimaryKeySelective(AdminDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Tue Apr 09 19:47:29 CST 2019
     */
    int updateByPrimaryKey(AdminDO record);
}