package com.otaku_tamashi.app.Dao;

import com.otaku_tamashi.app.POJO.DO.AnimeDataDO;
import org.springframework.stereotype.Repository;

@Repository
public interface AnimeDataDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    int insert(AnimeDataDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    int insertSelective(AnimeDataDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    AnimeDataDO selectByPrimaryKey(Long id);
    AnimeDataDO  selectByListID(Long list_id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    int updateByPrimaryKeySelective(AnimeDataDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anime
     *
     * @mbg.generated Mon Apr 08 20:52:26 CST 2019
     */
    int updateByPrimaryKey(AnimeDataDO record);
}