package com.otaku_tamashi.app.Dao;

import com.otaku_tamashi.app.POJO.DO.AnimeDO;
import com.otaku_tamashi.app.POJO.DO.FavouriteDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface FavouriteDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite
     *
     * @mbg.generated Tue Apr 09 16:48:52 CST 2019
     */
    int deleteByPrimaryKey(Long id);
    int deleteByUsernameAndId(@Param(value = "listid")long listid,@Param(value = "username") String username);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite
     *
     * @mbg.generated Tue Apr 09 16:48:52 CST 2019
     */
    int insert(FavouriteDO record);
    List<Long> selectFav(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite
     *
     * @mbg.generated Tue Apr 09 16:48:52 CST 2019
     */
    int insertSelective(FavouriteDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite
     *
     * @mbg.generated Tue Apr 09 16:48:52 CST 2019
     */
    FavouriteDO selectByPrimaryKey(Long id);
    FavouriteDO selectByUsernameAndListID(@Param(value = "listid")long listid,@Param(value = "username") String username);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite
     *
     * @mbg.generated Tue Apr 09 16:48:52 CST 2019
     */
    int updateByPrimaryKeySelective(FavouriteDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite
     *
     * @mbg.generated Tue Apr 09 16:48:52 CST 2019
     */
    int updateByPrimaryKey(FavouriteDO record);
}