package com.otaku_tamashi.app.Dao;

import com.otaku_tamashi.app.POJO.DO.NewsListDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface NewsListDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newslist
     *
     * @mbg.generated Mon Apr 08 12:35:05 CST 2019
     */
    int deleteByPrimaryKey(Long id);
    List<NewsListDO> selectByType(String type);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newslist
     *
     * @mbg.generated Mon Apr 08 12:35:05 CST 2019
     */
    int insert(NewsListDO record);
    List<NewsListDO> selectAll();
   Long selectByTitle(String title);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newslist
     *
     * @mbg.generated Mon Apr 08 12:35:05 CST 2019
     */
    int insertSelective(NewsListDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newslist
     *
     * @mbg.generated Mon Apr 08 12:35:05 CST 2019
     */
    NewsListDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newslist
     *
     * @mbg.generated Mon Apr 08 12:35:05 CST 2019
     */
    int updateByPrimaryKeySelective(NewsListDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newslist
     *
     * @mbg.generated Mon Apr 08 12:35:05 CST 2019
     */
    int updateByPrimaryKey(NewsListDO record);
}