package com.otaku_tamashi.app.Dao;

import com.otaku_tamashi.app.POJO.DO.UserDataDO;
import org.springframework.stereotype.Repository;

@Repository

public interface UserDataDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    int insert(UserDataDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    int insertSelective(UserDataDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    UserDataDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    int updateByPrimaryKeySelective(UserDataDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 06 16:01:24 CST 2019
     */
    int updateByPrimaryKey(UserDataDO record);
}